type: noatcards
contents:
  - file: TIL/2021-04-09/the-simple-magic-of-consistent-hashing.md
  - file: TIL/2021-04-09/introduction-to-architecting-systems-for-scale.md
  - file: TIL/2021-04-09/amazon-ElastiCache-for-redis.md
  - file: TIL/2021-04-09/cache_computing.md
